### ISSUE TITLE
Tool does not use .env file and environment variables.

### ISSUE THREAD

**Issue by Hikariii** [dzek69/docker-windows-notifier#3]
In a docker-compose file you are allowed to use `${VAR}`-like environment variables.

Compose files like this cannot be parsed correctly:
```yaml
version: '3.2'
services:
    nginx:
        image: nginx
        volumes:
            - ${PROJECT_ROOT}/assets:/assets
```

The given path will literally be interpreted as the string `${PROJECT_ROOT}/assets` which is incorrect.
