### ISSUE TITLE
Any clue why changes not being detected by webpack-dev-server inside container?

### ISSUE THREAD

**Issue by wintercounter** [dzek69/docker-windows-notifier#4]
wds is simply not catching changes. The notifier works (prints debug message on change). Polling is disabled in config so it should listen to native changes but it simply does nothing. Any idea where to start debug?

UPDATE: First change triggers compile fine but nothing happens with triggers after that.

UPDATE2: Tried some sysctl tweaks, none helped.

UPDATE3: Tried to debug with `inotifywatch ./` and no events were arriving at all.

UPDATE4: I debugged your script and stat commands are being executed just fine. It's really strange, after a docker restart the first 1-2 change works, after that it stops working :S Same happens with the Py version too.

UPDATE5: Even echoing into the end of a file from within the container is not triggering compile also. So it's most probably my issue is not related to `docker-windows-notifier`. Would be nice to have a clue where to search further, I even started to debug watchpack's chokidar.

My docker-compose.yml:
```
version: "3.2"
services:
  app:
    container_name: msc-frontend
    image: node:latest
    build: .
    extra_hosts:
      - "localhost.foo.com:127.0.0.1"
    ports:
      - "3000:3000"
      - "9011:9011"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    privileged: true
```
